### ISSUE TITLE
how to convert wav to hca or awb

### ISSUE THREAD

**Issue by Token713** [Thealexbarney/VGAudio#106]
if a hca encrypted with a custon key，use vgmstream can decod,does it show that encode is feasible?
If possible，what is the convert command ,such as convert aaa.wav to bbb.hca(encrypted with a custon key).

**Comment by bxaimc** [comment]
You can’t make encrypted HCAs with this. Only with CRIWare’s official tools.

**Comment by Thealexbarney** [comment]
Added in e6e0700
