### ISSUE TITLE
How do I make a hca file header that is a C8 C3 C1 file?

### ISSUE THREAD

**Issue by huashao2019** [Thealexbarney/VGAudio#109]
I extracted some hca from the game, I found that their file headers are C8 C3 C1, now how do I generate such a file, the file headers I make using hcaenc are 48 43 41

Test hca download link https://www.lanzous.com/i4a3upc

**Comment by Thealexbarney** [comment]
Use the option `--keycode <key>` at the command line

**Comment by huashao2019** [comment]
So how do I write the command line？
VGAudioCli -b -i source -o dest --out-format hca --keycode<00000000D77A01>？

**Comment by Thealexbarney** [comment]
The key code should be in base 10
VGAudioCli -b -i source -o dest --out-format hca --keycode 14121473

**Comment by huashao2019** [comment]
I used this command, but the file header is still 48 43 41,please help me

**Comment by huashao2019** [comment]
Or how do I contact you, I want to spend  to get a converter

**Comment by Thealexbarney** [comment]
Use the latest build https://ci.appveyor.com/api/buildjobs/wa2ie68wd0eq51sw/artifacts/VGAudioCli.exe

**Comment by huashao2019** [comment]
Okay,thanks my bro
