### ISSUE TITLE
Any way to encode audio region metadata into a BFSTM?

### ISSUE THREAD

**Issue by jarnumber9** [Thealexbarney/VGAudio#125]
Not exactly sure where to ask this. I've been getting into modding music for Zelda: Breath of the Wild. The town themes in that game are unique because they cycle through day and night themes, along with smooth transitions between the two, with all those different tracks in the same audio file.

Using the VGAudio command line tool, I analyzed the metadata for one of the town themes and found a section called, "Audio Regions," which correspond nicely with the different sections and jump points in the track.

![vgaudio kakariko](https://user-images.githubusercontent.com/83233592/116286153-e3772c00-a75c-11eb-960b-6af6c2356814.png)

One person in the BotW modding community has figured out how to encode these regions into their music mods, but no one else has been able to figure it out. Is there an advanced function of VGAudio that I'm missing? Is it something that can come to VGAudio in the future if one doesn't exist yet? Are there tools out there currently that can encode these audio regions?

Thank you for any help you can provide, and sorry if this is the wrong spot for this.

**Comment by Thealexbarney** [comment]
There isn't an option in the command line tool, but the library allows writing regions in BFSTM files

**Comment by jarnumber9** [comment]
Ah, cool. I guess I just gotta keep my eyes open for a tool that uses that writing functionality. Thank you.
