### ISSUE TITLE
File doesn't contain enough data for 1131639922 samples - Donkey Konga rip

### ISSUE THREAD

**Issue by rgm89git** [Thealexbarney/VGAudio#129]
I'm trying to extract Donkey Konga's music files (dsp) but this error appeared.

`File doesn't contain enough data for 1131639922 samples`

HELP ME

**Comment by Thealexbarney** [comment]
It sounds like the game might be using a custom format with the .dsp extension. That samples value is `Cstr` in ASCII. vgmstream might be able to decode them

**Comment by rgm89git** [comment]
oh ok
