### ISSUE TITLE
[Closed, invalid issue] What's the correct settings to encode a custom music for Digimon Cyber Sleuth Complete Edition (Steam)?

### ISSUE THREAD

**Issue by danylopez123** [Thealexbarney/VGAudio#130]
First of all, i've managed to extract the .hca files using DSCSTools.
The files were located in the DSDBbgm.steam.mvgl file.

After extracting the songs, then i used VGAudio to re-conver an ADX custom music i've made a long time ago to .hca, it worked by still keeping the loop points and stuff but.. after doing a replacement to one of the original .hca files and repacking the extracted songs only with that edit to test it, i tried replacing the menu music and.. it sounds corrupted.

Is there a setting i didin't changed while doing the conversion?

**Comment by Thealexbarney** [comment]
Do the original .hca files have any encryption?

**Comment by danylopez123** [comment]
Sorry, im still new on this.
How can i check that to tell if is encrypted or not?

**Comment by danylopez123** [comment]
Actually, forget about it, seems that if i build the GitHub version instead of downloading the one from the releases fixed the problem after i recently found a guide.
Sorry for this useless Issue, forget about this... although im having quite some problems trying to build the GitHub version + i don't know how to install the NuGet as well.
