### ISSUE TITLE
how to convert so many wav file to hca

### ISSUE THREAD

**Issue by EbiDesa** [Thealexbarney/VGAudio#133]
hello
i want to convert so many wav files to hca format, but i dont know how VGAudio Work

you say must insert this comment:
VGAudioCli -b -i source -o dest --out-format hca

where this command must be insert?

**Comment by masagrator** [comment]
vgaudio is a CLI tool, so as any CLI tool must be used via terminal (linux/mac)/command prompt(windows)

Use google to learn about using them.

**Comment by EbiDesa** [comment]
tnx bro. i found the way by moving files and vgaudio to system32 folder. its work 😍

**Comment by masagrator** [comment]
Uh, technically you shouldn't use system32 except if it's absolutely necessary. Deleting file from this folder by mistake can have big consequences.
